### PR TITLE
Added Samsung, LG Theme

### LINKED ISSUE #78: Samsung, LG, HP Line Logo
Would you add Samsung, LG Vendor themes?

Samsung Vendor themes have 2 Variants.

* Samsung Logo Only - For Samsung Notebook Series, Samsung PCs
  * [Logo Link](https://upload.wikimedia.org/wikipedia/commons/b/b4/Samsung_wordmark.svg)
* Galaxy Book Logo - For Samsung Galaxy Book Line-Up 
  * Logo Font is Samsung Sharp Sans Bold.

Also, HP Line Logo needs for High-End Lineups.

### PR DESCRIPTION
**Pull request by kuroehanako**
# Description

I added new variant.

I don't know compress PNG Image File size. Sorry.

Fixes # (issue)
- closes #78

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project (correct file and folder structure)
- [x] The background image for theme is called ``background.png``
- [x] ``theme.txt`` has correct *'desktop-image: "background.png"'* attribute

### CODE REVIEW

**Comment by AdisonCavani** [comment]
Is this PR ready to merge?

**Comment by kuroehanako** [comment]
yes.

**Comment by AdisonCavani** [comment]
Thanks you for contributing

**Comment by AdisonCavani** [comment]
Thank you for contributing

**Comment by AdisonCavani** [comment]
Thanks you for contributing

**Pull request merged**
